// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KSUWEBPMOCAP.Migrations
{
    [DbContext(typeof(KSUWEBPMOCAPContext))]
    [Migration("20200410192805_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KSUWEBPMOCAP.Models.Assignment", b =>
                {
                    b.Property<int>("Assign_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Faculty_ID");

                    b.Property<string>("Faculty_LastName");

                    b.Property<string>("Net_ID");

                    b.Property<int>("Project_ID");

                    b.Property<int?>("Student_ID");

                    b.Property<string>("Student_LastName");

                    b.Property<string>("Student_Net_ID");

                    b.HasKey("Assign_ID");

                    b.HasIndex("Faculty_ID");

                    b.HasIndex("Project_ID");

                    b.HasIndex("Student_ID");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.Department", b =>
                {
                    b.Property<int>("Dept_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssignmentAssign_ID");

                    b.Property<string>("Dept_Name");

                    b.Property<int>("Dept_Num");

                    b.Property<string>("Faculty_LastName");

                    b.Property<int?>("Project_ID");

                    b.HasKey("Dept_ID");

                    b.HasIndex("AssignmentAssign_ID");

                    b.HasIndex("Project_ID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.Faculty", b =>
                {
                    b.Property<int>("Faculty_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DepartmentDept_ID");

                    b.Property<string>("Dept_Name");

                    b.Property<string>("Faculty_Email");

                    b.Property<string>("Faculty_FirstName");

                    b.Property<string>("Faculty_LastName");

                    b.Property<string>("Net_ID");

                    b.HasKey("Faculty_ID");

                    b.HasIndex("DepartmentDept_ID");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.PDFFILE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Data");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("PDFFILE");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.Project", b =>
                {
                    b.Property<int>("Project_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dept_Name");

                    b.Property<DateTime>("EndDate");

                    b.Property<int?>("Faculty_ID");

                    b.Property<string>("Faculty_LastName");

                    b.Property<string>("Num_Teams_Sponsored");

                    b.Property<string>("Proj_Sponsor_Benefit");

                    b.Property<string>("Proj_Student_Benefit");

                    b.Property<string>("Proj_Type");

                    b.Property<bool>("Proj_hasNDA");

                    b.Property<string>("Project_Description");

                    b.Property<int?>("Project_ID1");

                    b.Property<string>("Project_Num");

                    b.Property<int?>("Sponsor_ID");

                    b.Property<string>("Sponsor_Name");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Project_ID");

                    b.HasIndex("Faculty_ID");

                    b.HasIndex("Project_ID1");

                    b.HasIndex("Sponsor_ID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.Proposal", b =>
                {
                    b.Property<int>("Propasal_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DepartmentDept_ID");

                    b.Property<string>("Dept_Name");

                    b.Property<int?>("Project_ID");

                    b.Property<int>("Project_Num");

                    b.Property<string>("Project_Type");

                    b.Property<int>("Sponsor_ID");

                    b.Property<string>("Sponsor_Name");

                    b.HasKey("Propasal_ID");

                    b.HasIndex("DepartmentDept_ID");

                    b.HasIndex("Project_ID");

                    b.HasIndex("Sponsor_ID");

                    b.ToTable("Proposal");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.RegUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Net_ID");

                    b.Property<byte>("Password");

                    b.HasKey("ID");

                    b.ToTable("RegUser");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.Sponsor", b =>
                {
                    b.Property<int>("Sponsor_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Sponsor_Address");

                    b.Property<string>("Sponsor_Email");

                    b.Property<string>("Sponsor_Name");

                    b.Property<string>("Sponsor_Org");

                    b.Property<string>("Sponsor_Phone");

                    b.Property<string>("Sponsor_Title");

                    b.Property<string>("Sponsor_Website");

                    b.HasKey("Sponsor_ID");

                    b.ToTable("Sponsor");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.Student", b =>
                {
                    b.Property<int>("Student_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Student_Email");

                    b.Property<string>("Student_FirstdName");

                    b.Property<string>("Student_LastName");

                    b.Property<string>("Student_Net_ID");

                    b.HasKey("Student_ID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.TblFile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContenType");

                    b.Property<string>("Data");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("TblFile");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.Assignment", b =>
                {
                    b.HasOne("KSUWEBPMOCAP.Models.Faculty")
                        .WithMany("Assignments")
                        .HasForeignKey("Faculty_ID");

                    b.HasOne("KSUWEBPMOCAP.Models.Project")
                        .WithMany("Assignments")
                        .HasForeignKey("Project_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KSUWEBPMOCAP.Models.Student")
                        .WithMany("Assignments")
                        .HasForeignKey("Student_ID");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.Department", b =>
                {
                    b.HasOne("KSUWEBPMOCAP.Models.Assignment")
                        .WithMany("Departments")
                        .HasForeignKey("AssignmentAssign_ID");

                    b.HasOne("KSUWEBPMOCAP.Models.Project")
                        .WithMany("Departments")
                        .HasForeignKey("Project_ID");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.Faculty", b =>
                {
                    b.HasOne("KSUWEBPMOCAP.Models.Department")
                        .WithMany("Faculties")
                        .HasForeignKey("DepartmentDept_ID");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.Project", b =>
                {
                    b.HasOne("KSUWEBPMOCAP.Models.Faculty")
                        .WithMany("Projects")
                        .HasForeignKey("Faculty_ID");

                    b.HasOne("KSUWEBPMOCAP.Models.Project")
                        .WithMany("Projects")
                        .HasForeignKey("Project_ID1");

                    b.HasOne("KSUWEBPMOCAP.Models.Sponsor")
                        .WithMany("Projects")
                        .HasForeignKey("Sponsor_ID");
                });

            modelBuilder.Entity("KSUWEBPMOCAP.Models.Proposal", b =>
                {
                    b.HasOne("KSUWEBPMOCAP.Models.Department")
                        .WithMany("Proposals")
                        .HasForeignKey("DepartmentDept_ID");

                    b.HasOne("KSUWEBPMOCAP.Models.Project")
                        .WithMany("Proposals")
                        .HasForeignKey("Project_ID");

                    b.HasOne("KSUWEBPMOCAP.Models.Sponsor")
                        .WithMany("Proposals")
                        .HasForeignKey("Sponsor_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
